const Chapters = {
	Introduction = "Introduction",
	KnightEncounter = "KnightEncounter",
	KnightFinishPhaseOne = "KnightFinishPhaseOne",
	KnightFinishPhaseTwo = "KnightFinishPhaseTwo",
	PostKnight = "PostKnight",
	PreRook = "PreRook",
	RookFinishPhaseOne = "RookFinishPhaseOne",
	RookFinishPhaseTwo = "RookFinishPhaseTwo",
	PostRook = "PostRook",
	QueenFinishPhaseOne = "QueenFinishPhaseOne",
	QueenFinishPhaseTwo = "QueenFinishPhaseTwo",
	PostQueen = "PostQueen",
}

return Chapters
